name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AppiumLibrary repo
        uses: actions/checkout@v3
        with:
          path: rf-al

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: rf-al/setup.py

      - name: Install Appium
        run: npm install -g appium

      - name: Start up Appium
        run: |
          nohup appium --log-timestamp --log-no-colors > appium.log &
#         nohup appium --use-plugins=images,execute-driver --relaxed-security --log-timestamp --log-no-colors > appium.log &
#         appium
      - name: Start up adb
        run: |
          adb start-server
          emulator -list-avds
          emulator -avd Pixel_3a_API_34_extension_level_7_arm64-v8a

      - name: Checkout Eficode course
        uses: actions/checkout@v3
        with:
          repository: eficode-academy/rf-mobile-testing-appium
          path: eficode

      - name: Debug Step
        run: ls

      - name: Run sample test
        run: robot -v APPIUM_PORT:4723 eficode/examples/simple/basics.robot

      - name: Archive appium log
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log
